<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="NTS5CG7321YLY" name="runners.runner_login_valid_credentials_Test" tests="1" failures="0" timestamp="06 Sep 2018 10:42:36 GMT" time="0.429" errors="1">
  <testcase name="feature" time="0.429" classname="runners.runner_login_valid_credentials_Test">
    <error type="cucumber.runtime.CucumberException" message="cucumber.runtime.CucumberException: Arity mismatch: Step Definition &#039;stepdefinitions.stepdefinitions_test.s_B_is_launched() in file:/D:/work/eclipsprojects/com_s4b_cucumber/target/test-classes/&#039; with pattern [^S(\d+)B is launched$] is declared with 0 parameters. However, the gherkin step has 1 arguments [4]. 
Step: Given S4B is launched">
      <![CDATA[cucumber.runtime.CucumberException: cucumber.runtime.CucumberException: Arity mismatch: Step Definition 'stepdefinitions.stepdefinitions_test.s_B_is_launched() in file:/D:/work/eclipsprojects/com_s4b_cucumber/target/test-classes/' with pattern [^S(\d+)B is launched$] is declared with 0 parameters. However, the gherkin step has 1 arguments [4]. 
Step: Given S4B is launched
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: cucumber.runtime.CucumberException: Arity mismatch: Step Definition 'stepdefinitions.stepdefinitions_test.s_B_is_launched() in file:/D:/work/eclipsprojects/com_s4b_cucumber/target/test-classes/' with pattern [^S(\d+)B is launched$] is declared with 0 parameters. However, the gherkin step has 1 arguments [4]. 
Step: Given S4B is launched
at cucumber.runtime.StepDefinitionMatch.arityMismatch(StepDefinitionMatch.java:102)
at cucumber.runtime.StepDefinitionMatch.transformedArgs(StepDefinitionMatch.java:60)
at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37)
at cucumber.runtime.Runtime.runStep(Runtime.java:300)
at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
at cucumber.runtime.model.CucumberScenario.runBackground(CucumberScenario.java:59)
at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:42)
at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
... 26 more
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- runners.runner_login_valid_credentials_Test -->
